name: Back-end

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd server && npm i
      - name: Run server
        run: cd server && npm run build

  test:
    runs-on: ubuntu-latest

    services: 
      postgres: 
        image: postgres
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: minig
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    
    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/minig"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd server && npm i
      - name: Prisma generate 
        run: cd server && npx prisma generate
      - name: Prisma migrations
        run: cd server && npx prisma migrate dev --name init
      - name: Run tests
        run: cd server && npm run test:prod

